config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :weetups do
    resources :comments
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      resources :weetups, only: [:index]
    end
  end

  root 'weetups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :weetup, counter_cache: true

  validates :content, presence: true
  scope :recent, -> {order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :weetups
  has_many :comments

  before_create :generate_authentication_token

  def generate_authentication_token
     self.authentication_token = Devise.friendly_token
  end  
end

app/models/weetup.rb
class Weetup < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, presence: true
  scope :recent, -> {order("created_at DESC")}
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  attr_accessor :current_user
  # disable the CSRF token
  protect_from_forgery with: :null_session

  # disable cookies (no set-cookies header in response)
  before_action :destroy_session

  # disable the CSRF token
  skip_before_action :verify_authenticity_token

  def destroy_session
    request.session_options[:skip] = true
  end

  def authenticate_user!
    token, options = ActionController::HttpAuthentication::Token.token_and_options(request)

    user_email = options.blank?? nil : options[:email]
    user = user_email && User.find_by(email: user_email)

    if user && ActiveSupport::SecurityUtils.secure_compare(user.authentication_token, token)
      self.current_user = user
    else
      return unauthenticated!
    end
  end

  def unauthenticated!
    api_error(status: 401)
  end

  def api_error(opts = {})
    render nothing: true, status: opts[:status]
  end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::BaseController
  def create
    @user = User.find_by(email: create_params[:email])
    if @user && @user.valid_password?(create_params[:password])
      sign_in :user, @user
    else
      return api_error(status: 401)
    end
  end

  private

  def create_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  before_action :authenticate_user!, only: [:update]

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(update_params)
  end

  private

  def update_params
    params.require(:user).permit(:name)
  end

end

app/controllers/api/v1/weetups_controller.rb
class Api::V1::WeetupsController < Api::V1::BaseController
   before_action :authenticate_user!, only: [:index]

  def index
    @weetups = Weetup.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]

  def new
    @weetup = Weetup.find(params[:weetup_id])
    @comment = Comment.new
  end

  def create
    @weetup = Weetup.find(params[:weetup_id])
    @comment = Comment.new(comment_params)
    @comment.weetup = @weetup
    @comment.user = current_user

    if @comment.save
      redirect_to weetup_path(@weetup)
    else
      render :new
    end
  end

  def edit
    @weetup = Weetup.find(params[:weetup_id])
    @comment = Comment.find(params[:id])
    @comment.weetup = @weetup
  end

  def update
    @weetup = Weetup.find(params[:weetup_id])
    @comment = Comment.find(params[:id])
    @comment.weetup = @weetup
    @comment.user = current_user
    if @comment.update(comment_params)
      redirect_to weetup_path(@weetup), notice: "编辑成功"
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to weetups_path, alert: "删除留言成功"
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/weetups_controller.rb
class WeetupsController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy]
  before_action :find_weetup_and_check_permission, only: [:edit, :update, :destroy]
  def index
    @weetups = Weetup.all.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @weetup = Weetup.find(params[:id])
    @comments = @weetup.comments.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @weetup = Weetup.new
  end

  def create
    @weetup = Weetup.new(weetup_params)
    @weetup.user = current_user

    if @weetup.save
      redirect_to weetups_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @weetup.update(weetup_params)
      redirect_to weetups_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @weetup.destroy
    redirect_to weetups_path, alert: "Meetup deleted"
  end

  private

  def find_weetup_and_check_permission
    @weetup = Weetup.find(params[:id])

    if current_user != @weetup.user
      redirect_to root_path, alert: "You have no permission"
    end
  end

  def weetup_params
    params.require(:weetup).permit(:title, :description)
  end
end

app/helpers/api/v1/base_helper.rb
module Api::V1::BaseHelper
end

app/helpers/api/v1/sessions_helper.rb
module Api::V1::SessionsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/api/v1/weetups_helper.rb
module Api::V1::WeetupsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/weetups_helper.rb
module WeetupsHelper
end

app/views/comments/edit.html.erb
<h2 class="text-center">编辑</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@weetup,@comment] do |f| %>
    <div class="form-weetup">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "发送", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/comments/new.html.erb
<h2 class="text-center">留言</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@weetup,@comment] do |f| %>
    <div class="form-weetup">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "发送", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"> meetup </a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登录", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render "common/navbar" %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/weetups/_comment_form.html.erb
<%= form_for(Comment.new, url: weetup_comments_path(@weetup)) do |f| %>
  <%= f.text_area :content %>
  <%= f.submit "发言", :disable_with => 'Submiting...' %>
<% end %>

app/views/weetups/_form.html.erb
<%= simple_form_for @weetup do |f| %>
  <div class="form-weetup">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "确定", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/weetups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑</h2>

    <hr>

    <%= render "form" %>
    
</div>

app/views/weetups/index.html.erb
<div class="col-md-12">
  <div class="weetup">
    <%= link_to("New meetup", new_weetup_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>城市</td>
        <td>详情</td>
        <td>组织者</td>
        <th>发表时间</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @weetups.each do |weetup| %>
        <tr>
          <td>#</td>
          <td><%= link_to(weetup.title, weetup_path(weetup)) %></td>
          <td><%= weetup.description %></td>
          <td><%= weetup.user.email %></td>
          <td><%= weetup.created_at.strftime("%Y/%m/%d %I:%M %p") %></td>
          <td>
              <% if current_user && current_user == weetup.user %>
              <%= link_to("编辑", edit_weetup_path(weetup), class: "btn btn-sm btn-default")%>
              <%= link_to("删除", weetup_path(weetup),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: " 确定删除吗？" } )%>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h2>聚会查询</h2>

  <% if current_user %>
    <p>已经登入：你的 API token 是 <code><%= current_user.authentication_token  %></code></p>
  <% else %>
    <p>尚未登入</p>
  <% end %>
</div>

app/views/weetups/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>创建</h2>

    <hr>

    <%= render "form" %>

</div>

app/views/weetups/show.html.erb
<div class="col-md-12">
  <div class="weetup">

    <%= link_to("留言", new_weetup_comment_path(@weetup), class: "btn btn-default pull-right")%>

    <% if current_user && current_user == @weetup.user %>
    <%= link_to("编辑", edit_weetup_path(@weetup), class: "btn btn-primary pull-right")%>
    <% end %>
  </div>
  <h2><%= @weetup.title %></h2>
  <p><%= @weetup.description %></p>


  <% if @comments.empty? %>
  <p> 尚未有人留言 </p>
<% else %>
  <% @floor = 1 %>
  <table class="table">
    <thead>
      <tr>
        <th>楼层</th>
        <th>留言</th>
        <th>发表者</th>
        <th>发表时间</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
  <% @comments.each do |comment| %>

    <tr>
      <td><%= @floor %>楼</td>
      <% @floor = @floor + 1 %>
      <td><%= comment.content %></td>
      <td><%= comment.user.email %></td>
      <td><%= comment.created_at.strftime("%Y/%m/%d %I:%M %p") %></td>
      <% if current_user && current_user == @weetup.user %>
      <td> <%= link_to('编辑', edit_weetup_comment_path(comment.weetup, comment), class: "btn btn-default btn-xs") %></td>
      <td> <%= link_to('删除', weetup_comment_path(comment.weetup, comment), method: :delete, data: { confirm: " 你确定删除吗？" }, class: "btn btn-default btn-xs") %></td>
      <% end %>
    </tr>
  <% end%>
</tbody>
</table>

<% end %>


<%= render 'comment_form' %>

<div class="text-center">
  <%= will_paginate @comments %>
</div>
</div>